{
 "title": "namada-validators",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "validator",
    "query": {
     "query": "label_values(namada_node_catch_up,validator_tm_address)"
    }
   },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator set",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(1, namada_network_max_set_size)",
     "legendFormat": "max_set"
    },
    {
     "expr": "topk(1, namada_network_active_set_size)",
     "legendFormat": "active_set"
    }
   ]
  },
  {
   "title": "Network epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(1, namada_network_epoch)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lowest stake in network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, namada_network_lowest_active_set_stake)",
     "legendFormat": "lowest stake in network"
    }
   ]
  },
  {
   "title": "Stake threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, namada_network_stake_threshold)",
     "legendFormat": "threshold"
    }
   ]
  },
  { "title": "VALIDATOR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_uptime_percentage{validator_tm_address=~\"$validator\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Missed blocks in window",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_missed_blocks{validator_tm_address=~\"$validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NODE SYNC?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_node_catch_up{validator_tm_address=~\"$validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest block from validator RPC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_node_latest_block{validator_tm_address=~\"$validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest block from validator RPC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_active_set_rank{validator_tm_address=~\"$validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator state ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_validator_state{validator_tm_address=~\"$validator\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}